import { Book } from "@/types"; 


export const initialBooks: Book[] = [
  {
    id: "1",
    title: "O Senhor dos Anéis",
    author: "J.R.R. Tolkien",
    genre: "Fantasia",
    year: 1954,
    pages: 1216,
    pagesread: 1216,
    status: "LIDO",
    finishDate: "2023-01-15",
    rating: 5,
    synopsis: "A jornada de Frodo Bolseiro para destruir o Um Anel.",
    cover: "https://covers.openlibrary.org/b/id/823274-L.jpg",
    imageurl: "https://covers.openlibrary.org/b/id/823274-L.jpg",
    created_at: "2023-01-01",
    owner: "user_id_placeholder",
  },
  {
    id: "2",
    title: "1984",
    author: "George Orwell",
    genre: "Distopia",
    year: 1949,
    pages: 328,
    pagesread: 150,
    status: "LENDO",
    finishDate: null,
    rating: 4,
    synopsis: "Um futuro sombrio onde o Grande Irmão vigia a todos.",
    cover: "https://covers.openlibrary.org/b/id/823274-L.jpg",
    imageurl: "https://covers.openlibrary.org/b/id/823274-L.jpg",
    created_at: "2023-05-20",
    owner: "user_id_placeholder",
  },
  {
    id: "3",
    title: "Cem Anos de Solidão",
    author: "Gabriel García Márquez",
    genre: "Realismo Mágico",
    year: 1967,
    pages: 417,
    pagesread: 0,
    status: "QUERO_LER",
    finishDate: null,
    rating: null,
    synopsis: "A história da família Buendía ao longo de sete gerações.",
    cover: "https://covers.openlibrary.org/b/id/823274-L.jpg",
    imageurl: "https://covers.openlibrary.org/b/id/823274-L.jpg",
    created_at: "2023-06-10",
    owner: "user_id_placeholder",
  },
];
